### PR TITLE
[MGR] Adding ignore mode in parafac (solving #72)

### PR DESCRIPTION
**Pull request by cohenjer**
Hi,

I have been working on my own fork of tensorly for some time now, and I though I might start adding some contributions the easy way, with some small tweaks.

Here is a proposed solution to #72 (Fixed modes in Parafac). Since the optimization algorithm is ALS, it is quite straighforward to implement this. I simply changed the loop condition to ignore modes given by the user.

Sorry for the messy PR, there are many line-removal / blank removal... Also there are changes to README and to .gitignore that should absolutely not be pulled, but I don't know how to make a partial PR :/ hope we can work this out easily.

In principal however this PR should be functionning, since I have been using it for some time now without issues.

### CODE REVIEW

**Comment by cohenjer** [comment]
I should mention there are tons of useless commits here that relate to other contributions I plan to make later on. If it makes things clearer I can make a fresh fork with only this PR.

**Comment by asmeurer** [comment]
@cohenjer you don't need to make another fork. Rather you should make a separate branch. You can use `git cherry-pick` to choose only those commits that are relevant to a given PR.

**Comment by cohenjer** [comment]
Let me remake this PR properly. I'll refork the project, and commit this PR in its own branch.

**Comment by JeanKossaifi** [comment]
Great, thanks @cohenjer and @asmeurer.

**Pull request closed without merging**
