### PR TITLE
Also provide H back from make_svd_non_negative()

### LINKED ISSUE #515: make_svd_non_negative only returns the updated U matrix
#### Describe the bug
I'm not sure if this is a bug or if this is actually how this function is supposed to behave but currently, it only returns the updated U value. Incase it's not a bug, I don't understand why the H matrix is computed in this function (https://github.com/tensorly/tensorly/blob/6c7ecfbfbfc088cb1a423e6a5970e19565844651/tensorly/tenalg/svd.py#L65)

Looking forward to your response.

### PR DESCRIPTION
**Pull request by aarmey**
Fixes #515

### CODE REVIEW

**Comment by hello-fri-end** [comment]
Hello @aarmey! Maybe we should loop till len(S) in the following line since the no. of columns of U may not be equal to the number of rows of V:
https://github.com/tensorly/tensorly/blob/b99cb2c4909db2e2285c460d66eec155ca2be704/tensorly/tenalg/svd.py#L90

**Comment by JeanKossaifi** [comment]
Thank you @aarmey - it looks good to me!

@hello-fri-end that's a good point but it shouldn't matter - that potential "extra" block should be zero and associated with just a 1 on the diagonal of S right?

**Comment by hello-fri-end** [comment]
> Thank you @aarmey - it looks good to me!
> 
> @hello-fri-end that's a good point but it shouldn't matter - that potential "extra" block should be zero and associated with just a 1 on the diagonal of S right?

Hey @JeanKossaifi, thanks for the reply! Assuming, `U`, `S`,  and `V` are the output of economy SVD, it will never fail. I was just thinking if `U.shape == ( m x m )`,` S.shape == ( m x n )`  and `V.shape == ( n  x n )`, given a matrix of shape `(m, n)` with `m > n`, then `V[j, :]` might throw an error in the following line:
https://github.com/tensorly/tensorly/blob/b99cb2c4909db2e2285c460d66eec155ca2be704/tensorly/tenalg/svd.py#L90-L91

**Comment by JeanKossaifi** [comment]
I see - this is a good point we don't know what was used to get U, S, V, should we loop until min(m, n) then? 
Could you maybe add a test case for this?

**Comment by aarmey** [comment]
I've fixed this issue, as well as #522, and added a test.

**Comment by JeanKossaifi** [comment]
Thanks a lot @aarmey! Looks great, merging.

**Comment by aarmey** [comment]
Thanks, @JeanKossaifi. Looks like there is a typing error with mxnet. I can fix that and then merge.

**Comment by JeanKossaifi** [comment]
Yes I just noticed :)

**Pull request merged**
