### PR TITLE
Add CP indexing function

### PR DESCRIPTION
**Pull request by aarmey**
To help with #352, this adds a very simple function to allow indexing the components within a CP tensor. This makes it a little simpler to permute or remove a component.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Hi @aarmey - thanks, this is a neat feature. 
Actually, I was hoping to slowly merge TensorLy-Torch's new tensor class within TensorLy itself and add general indexing. The advantage is that indexing a factorized indexing returns a factorized tensor when possible and a dense tensor otherwise:

https://github.com/tensorly/torch/blob/24bdae7b5b87548c7db37c6e9a53b03259ec2002/tltorch/factorized_tensors/factorized_tensors.py#L89


What do you think?

**Comment by aarmey** [comment]
Tests are still failing... looking into it.

**Comment by aarmey** [comment]
As far as I can tell, there is no front-end way to index an array consistently across backends. The current solution works for all but tensorflow. Unless we plan to change tensorflow to the experimental numpy interface soon, I'll add a backend function to help with indexing.

**Comment by JeanKossaifi** [comment]
Do you think we need a separate function to do this? If it's useful as it's done repetitively, perhaps we could call it something like index_cp_rank to differentiate it from indexing a tensor in factorized CP form? 

I'm happy to just skip the tensorflow test right now with pytest while we decide what to do with that backend.

**Comment by aarmey** [comment]
I agree about the renaming.

I'd be interested to learn a bit more about the backend plans when we talk tomorrow. I do use this frequently but would rather not merge it if it is broken for some backends. I can always stash this away until later.

**Pull request closed without merging**
