### PR TITLE
feat: add `pip` caching to CI

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Changes made by this PR can be summarized as follows:

- Set the `cache` and `cache-dependency-path` argument to enable caching to speed up CI times.

Request for Review: @JeanKossaifi

### CODE REVIEW

**Comment by SauravMaheshkar** [comment]
Huh, it seems like coverage is failing, but this PR simply changes the CI not the codebase, maybe it's just a codecov error ?

**Comment by SauravMaheshkar** [comment]
Yes @JeanKossaifi, For reference https://github.com/actions/setup-python#caching-packages-dependencies, outlines that cache won't be restored if a newer package version is available. In case of a new version, it downloads it and updates the cache.

**Comment by SauravMaheshkar** [comment]
Gentle ping @JeanKossaifi

**Comment by JeanKossaifi** [comment]
Thanks @SauravMaheshkar !
It looks good to me - the test doesn't use the doc requirements. Perhaps we can update the PR cache only reqs here and add doc reqs caching to the doc CI script?

**Comment by SauravMaheshkar** [comment]
Makes sense, addressed in e9970122ec073be6b2a3b03256dadea123cd4e53

**Comment by SauravMaheshkar** [comment]
Looks like everything passed 😄

**Comment by JeanKossaifi** [comment]
Thanks @SauravMaheshkar, looks great to me! Could you maybe add a small note in the documentation about this for future users/maintainers?

**Comment by SauravMaheshkar** [comment]
> Thanks @SauravMaheshkar, looks great to me! Could you maybe add a small note in the documentation about this for future users/maintainers?

Yeah sure, will do

**Pull request merged**
