### PR TITLE
adding indian pines locally and updating loader

### LINKED ISSUE #465: fetch_indian_pines broken
fetch_indian_pines (and therefore it's test) fail, e.g. https://github.com/tensorly/tensorly/actions/runs/3660881883/jobs/6198153331

This seems to be due to the server hosting the data not supporting Open SSL 3
https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled

# Todo
- [ ] Remove test skip when fixed  #465

### PR DESCRIPTION
**Pull request by cohenjer**
Fixes #465 by adding the Indian pines data and ground truth locally. License allows redistributing the data as long as the original work is credited.

### CODE REVIEW

**Comment by cohenjer** [comment]
I can convert the data to .npy if someone thinks it's better for some reason.

**Review by aarmey — APPROVED** [review]
This looks good to me.

**Comment by JeanKossaifi** [comment]
Looks good to me too - I'd like to have an `npy` file instead of `.mat` as it's more pythonic!

**Comment by cohenjer** [comment]
> Looks good to me too - I'd like to have an `npy` file instead of `.mat` as it's more pythonic!

Will do asap !

**Review by JeanKossaifi — APPROVED** [review]
Fabulous, thanks @cohenjer!

**Pull request merged**
