### PR TITLE
Reworking nonnegative algorithm and solvers

### PR DESCRIPTION
**Pull request by cohenjer**
First of all, I am sorry for the massive PR with so many small commits (to be squashed upon merge hopefully). I have been working on this for quite some time, and cutting this work into pieces seemed artificial and challenging.

Anyways I hope to make the nonnegative things in Tensorly a little cleaner and efficient with this!

# Improvements for NNLS
- Fixed Nonnegative Least Squares (NNLS) solvers (HALS, FISTA) that had bugs in them.
- Added ridge and sparse regularization support for all NNLS solvers and HALS algorithms.
- Replaced return_errors with callback for all nonnegative solvers (also Multiplicative Updates solvers). Added documentation which was missing for callback.
- Added the option to have unconstrained modes in ``non_negative_tucker_hals`` (this is now similar to ``non_negative_parafac_hals`` API)
- The error computation (math and code) were different in the various nonnegative decomposition algorithms. I chose to unify them, computing the loss function. This is not what is done in the CP function (we compute the square-root of the loss); this is open to discussion, but showing the loss is what makes the most sense to me. I updated the CP functions as well to have at least the same math for ``tensor_norm`` everywhere.
- Updated API for HALS function to allow some degree of control over the inner HALS nnls solver. But I also simplified the nnls HALS API so these new inputs should be self-explanatory.
- Reworked documentation (a lot) to add some missing arguments, and improve clarity.
- Updated the nonnegative decomposition examples to make them easier to follow and simpler. Also they now explain random tensor generations and parameter tuning in the algorithms.
- Of course, modified the tests where needed, and added new ones for the solvers/ (see below)

# Overall improvements
- Reverted MTTKRP back to the faster matrix-matrix product. I added the current memory-efficient version too, with some snippet of code in the documentation to show how to switch from one to the other using the backend system. This makes all CP algorithms significantly faster as we discussed here #442 
- Created a solvers/ folder in tensorly, to move all the optimization methods from tenalg/ to a dedicated place. solvers/ has four modules (``nnls.py``, ``admm.py``, ``proximal.py`` and ``penalizations.py``, this last one being mostly empty but I plan to populate it in a coming PR).

# Others
- Adding the maximum() function in the backend, useful for nonnegative projections.

# Pending
- The FISTA algorithm in HALS for nonnegative Tucker needs a stepsize, right now I use some hand-crafted scheduling (compute the Lipschitz constant for first 20 outer iterations which are critical, then update every 20 iterations). Is this satisfactory? If yes I can add some documentation for this.
- There are some tests which are not passing, but I am unsure if this is due to bugs introduced by this PR (probably not). One test however that failed after changing back the MTTKRP to the matrix-matrix product version is ``test_entropy.py``. I had to comment out the test with normalization activated, I have no explanation as to why that failed...

### CODE REVIEW

**Comment by aarmey** [comment]
@cohenjer this is outstanding! Many thanks.

I agree about splitting this up. For instance, perhaps much of the (1) documentation, (2) return_errors interface, (3) MTTKRP, and (4) tl.maximum changes can be separate PRs? I'm happy to quickly review each if so. It's **so** easy to miss bugs otherwise...

I am strongly in favor of using a consistent loss throughout (and having it be the loss, not the square root)! This inconsistency has tripped me up several times.

**Comment by aarmey** [comment]
One method that has helped me is to make a new branch, then `git checkout old_branch -- file_path`. This way you can copy over a file and changes to a new branch without having to manually copy and paste.

**Comment by JeanKossaifi** [comment]
Great suggestion @aarmey - we should have a section in the contribution doc to collate all these tips!

**Comment by cohenjer** [comment]
Working on this right now, should be creating a few PRs soon !

**Comment by JeanKossaifi** [comment]
Should we close this @cohenjer ?

**Comment by cohenjer** [comment]
Hi @JeanKossaifi yes we can close this one, since #542 (and subsequent PRs that are queuing) cover the same contribution.

**Pull request closed without merging**
