### PR TITLE
Making partial_svd and tucker reproducible

### PR DESCRIPTION
**Pull request by lan496**
fix https://github.com/tensorly/tensorly/issues/138

- ~~I add the option of a starting vector for `scipy.sparse.linalg.eigsh` in `tensorly.partial_SVD`~~
- I also append a test checking if the same result for partial SVD is obtained.

I've checked my commit passes all the tests by `make test`.

### CODE REVIEW

**Comment by lan496** [comment]
Sorry, this fix is not compatible with backends other than numpy.
I'll handle it.

**Comment by lan496** [comment]
I've handled multiple backends.
And I've changed the code of Tucker decomposition to be deterministic with random_state.

**Comment by JeanKossaifi** [comment]
Hi @lan496,
Thanks for the issue and PR to fix it!

> Sorry, this fix does not seem to be compatible with backends other than numpy.
> I'll handle it.

I like the attitude! :D

The fix looks great. One thing: rather than inspecting the signature of the SVD fun and creating a partial version, we could just add a **kwargs in all and use `random_state` when relevant?

**Comment by lan496** [comment]
Thank you for your suggestion, @JeanKossaifi .
I add kwargs for all the SVD functions: That's more flexible!

**Comment by JeanKossaifi** [comment]
Thanks @lan496! 

Just a comment regarding the initialization of `v0`: in general initializing correctly these algorithms is not trivial:
* If `random_state is None`, I would initialize `v0` to `None`: it is better to let Arpack choose the init.
* I also do not think that rand is the most appropriate choice, see [discussion in scikit-learn](https://github.com/scikit-learn/scikit-learn/pull/5012) and [doc of Arpack](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dgetv0.f#L225). We should probably at least use a uniform distribution in [-1, 1].

Looks good otherwise!

**Comment by lan496** [comment]
I'm done.
Honestly, I wasn't confident with how to initialize `v0`. So thank you for sharing the related discussion and docs.

**Comment by JeanKossaifi** [comment]
Awesome, thanks @lan496, merging!

**Pull request merged**
