### PR TITLE
Fix TypeError run tensorly.partial_svd with None n_eigenvecs

### LINKED ISSUE #120: tensorly.partial_svd raise TypeError when n_eigenvecs is None
It seems `n_eigenvecs` should be checked `None` before comparing with `min_dim`

```
...
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/tensorly/backend/numpy_backend.py", line 219, in partial_svd
    if n_eigenvecs >= min_dim:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

### PR DESCRIPTION
**Pull request by kingsj0405**
Fix #120

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thanks for the PR.
There is a small issue with `full_matrices`, you discarded one of the cases in the process.

**Comment by kingsj0405** [comment]
Yeah, and I'll check test validation ASAP...

**Comment by JeanKossaifi** [comment]
@kingsj0405 just checking whether you are still working on this?

**Comment by kingsj0405** [comment]
@JeanKossaifi Sorry, I forgot this issue. Added on my TODO list now.

**Comment by kingsj0405** [comment]
Close and open new pull-request #144 to solve skewed commit problem

**Pull request closed without merging**
