### PR TITLE
Remove mxnet

### PR DESCRIPTION
**Pull request by aarmey**
This removes mxnet as a backend, since development has halted.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Shall we merge this @aarmey ?

**Comment by aarmey** [comment]
@JeanKossaifi I'm fine with merging, unless you think we should issue a new version with the deprecation warning that currently exists on main?

**Comment by aarmey** [comment]
Actually, I think this is important to merge now. It looks like the mxnet repository has been fully archived. The changes here to remove mxnet from the documentation will avoid confusion in the future. Merging.

**Comment by JeanKossaifi** [comment]
Thanks @aarmey !

**Comment by JeanKossaifi** [comment]
Should we also start removing TensorFlow @aarmey ?

**Comment by aarmey** [comment]
I don't think anything has changed since the #490 discussion? TF is at least not outright broken, so there's no rush for deprecating it. On the other hand, if it isn't being used, simplifying the codebase only helps.

**Comment by bakhtos** [comment]
Hello,

The website of tensorly still promises MxNet.
Screenshot 2024-01-31 at 13 43 20

**Comment by JeanKossaifi** [comment]
Thanks @bakhtos - we'll update the doc! Feel free to open a small PR if you are able to! :) 
I opened an issue to track.

**Pull request merged**
