### PR TITLE
Add lstsq to backend

### PR DESCRIPTION
**Pull request by merajhashemi**
This PR adds `lstsq`, a function that computes the minimum norm least squares solution, to the backend.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thanks @merajhashemi! I don't think we need to just return the solution, e.g. the residuals etc are also useful.

**Comment by merajhashemi** [comment]
@JeanKossaifi TensorFlow and PyTorch(<1.9) do not return the rank and singular values, and also TensorFlow doesn't return the residuals. I'm not sure if it's worth adding an extra call to `svd` and `matrix_rank`.

**Comment by JeanKossaifi** [comment]
Hmm - perhaps we can add at least the residuals and just compute that in the TensorFlow case? We're thinking of dropping tf backend anyway, and JAX is more powerful and flexible.

**Comment by JeanKossaifi** [comment]
Looks great @merajhashemi, merging!

**Pull request merged**
