### PR TITLE
Decorator for backend specific implementations

### PR DESCRIPTION
**Pull request by MarieRoald**
@yngvem and I implemented a decorator for backend specific functions (with tests and documentation) as described in #432

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
I love it @MarieRoald @yngvem!

I wonder whether we would also want to expand it even slightly more for cases where we want to override a function for all backends. A specific usecase I have in mind is einsum -- I've been working on an interface to change the einsum function to i) e.g. use opt-einsum and ii) cache the contraction path. 

Seems like this could be achieved with this PR as well, what do you think?

**Comment by MarieRoald** [comment]
I really like the idea of caching the contraction path/using opt-einsum! Do you have a specific API in mind? Are you for example thinking that the einsum is automatically overriden if opt-einsum is installed?

**Comment by JeanKossaifi** [comment]
No, exactly, I'm thinking it should be optional, and such a decorators might be the way to go? 
e.g. we could have a function like `override_function(existing_fun, new_fun, backend=None)` to apply the decorator, and further provide a facility such as `use_opt_einsum()` or `set_einsum`?

**Comment by JeanKossaifi** [comment]
Another thing: should we add the new function to the list of functions available to that backend when we wrap it? 
Perhaps we can add a Notes section to the docstring too so users know how this is done - that their function is just going the wrapped?

**Comment by yngvem** [comment]
Hmmm. I think we could do something like that :) But I think it would be nice to discuss it in a separate issue/PR to make it easier to see where the different changes were introduced and why we added this feature. I made an issue (https://github.com/tensorly/tensorly/issues/452) for tracking this as best as I understand it, and I think we can start implementing it soon.

**Comment by JeanKossaifi** [comment]
Sounds great - what should we do with this PR? Should we merge as is and iterate?

**Pull request merged**
