### PR TITLE
Use UTF-8 encoding

### LINKED ISSUE #122: Encoding error on 'pip install -e .'
```
$ pip install -e .
Obtaining file:///app/sejong/tensorly
    ERROR: Command errored out with exit status 1:
     command: /home/user/miniconda/envs/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/sejong/tensorly/setup.py'"'"'; __file__='"'"'/app/sejong/tensorly/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /app/sejong/tensorly/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/app/sejong/tensorly/setup.py", line 44, in <module>
        README = readme(root_path)
      File "/app/sejong/tensorly/setup.py", line 40, in readme
        return f.read()
      File "/home/user/miniconda/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1519: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### PR DESCRIPTION
**Pull request by kingsj0405**
Fix #122

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Strange, I did not have any issue. Any idea why this appeared for you?

**Comment by asmeurer** [comment]
It's probably locale specific (depending on the value of the `LANG` environment variable). I think these sorts of things can be particularly bad in Docker containers.

**Comment by kingsj0405** [comment]
@asmeurer Exactly, it's on my own docker container forked from `pytorch/pytorch`

**Comment by JeanKossaifi** [comment]
Awesome, thanks!

**Pull request merged**
