### PR TITLE
Sparse docs

### PR DESCRIPTION
**Pull request by asmeurer**
Here are some documentation for sparse arrays. 

This is based on the branch from https://github.com/tensorly/tensorly/pull/85, so that should be reviewed and merged first. It also references the robust_pca work which is forthcoming, and it also references the notebook from the pull request https://github.com/JeanKossaifi/tensorly-notebooks/pull/6.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thanks - great addition, it will be very helpful for both new users and new devs!

**Comment by JeanKossaifi** [comment]
Might be easier to just copy the changes to the doc in a new PR than manually fix the merge conflicts at this point.

**Comment by asmeurer** [comment]
The branches should all be based off each other (I never rebased). Unless that's not the case, git should merge cleanly once the upstream is merged in because the conflicts have already been resolved (git rerere also remembers conflict resolutions if you have it enabled). I'll take a look once the other branch is merged in.

**Comment by JeanKossaifi** [comment]
Thanks a lot @asmeurer  and @scopatz.
Updated slightly on top of your commits in #107.

**Pull request closed without merging**
