### PR TITLE
[Tracking] Major Parafac Improvements

### PR DESCRIPTION
**Pull request by cswiercz**
> This is a tracking PR for a collection of improvements to `parafac()`. I wanted to get @JeanKossaifi 's input before I dump a bunch of code into this PR.

# Sub-PRs

- [x] #32 Add functionality to backend
- [x] #33 Add where() to Pytorch backend
- [x] #34 Allow optional weights in kruskal_to_tensor
- [x]  #37 Refactor `parafac()` initialization
- [x] *Add Orthogonalized ALS*
- [ ] *Add Line Search*

# Description

In a personal, private branch of Tensorly I have implemented several improvements to `parafac()`. Primarily,

* Orthogonalized ALS [1] - QR-orthogonalizing the factor matrices in the first few iterations can lead to better local minima in fewer iterations, especially if the input tensor has orthogonal components.
* Enhanched Line Search [2] - technically, I only implemented a basic line search algorithm. Experiments show that line search improves convergence rates as well as helps the algorithm escape local minima more quickly.

I would like to add this private work to Tensorly. This work requires a bit of a refactor of the existing `parafac()` code so that it is easy to turn these options on and off as well as makes the existing code more easily extendible. Below I included some arguments to the effectiveness of these "augmentations". Please let me know if this sounds good or if you have any concerns. I will be posting the actual code (and many many tests) in this PR soon.

# Experimental Data

The two plots below are typical examples of the reconstruction error improvement on random noisly orthogonal order three tensors. (The following code shows how these tensors are generated with `noisy = True`.) The figures below compare iteration count vs. reconstruction error between "vanilla" alternating least squares (ALS) and adding combinations of line search (LS) and QR orthogonalization (QR). The dashed black line indicates the L2-norm of the added noise which is the absolute best we can do in estimating the tensor as a sum of orthogonal components.

```python
def generate_random_tensor(dimensions=(10,10,10), rank=10, seed=0,
                           orthogonal=False, near_orthogonal=False, noisy=False):
    order = len(dimensions)
    dim = min(dimensions)
   if (rank > dim) and (orthogonal or near_orthogonal):
       raise ValueError('Can only construct orthogonal and near-orthogonal '
                        'tensors when rank <= min(dimensions)')

    np.random.seed(seed)
    weights = 4*tensorly.arange(1, rank+1).astype('float32')
    factors = map(tensorly.tensor, (np.random.randn(dim,rank) for dim in dimensions))

   if orthogonal:
        factors = map(lambda X: tensorly.qr(X)[0], factors)
    T = tensorly.kruskal_to_tensor(factors, weights)

   if noisy:
        scale = rank/(rank+32.)  # theoretical error approx. 1e-2 to 1e-3
        T += tensorly.tensor(scale*np.random.randn(*dimensions))
   return T, factors, weights
```

# References

> [1] V. Sharan and G. Valliant, *"Orthogonalized ALS: A Theoretically Principled Tensor Decomposition Algorithm for Practical Use"*, Proceedings of the 34th International Conference on Machine Learning, PMLR 70, 2017
> [2] M. Rajih, et. al., *"Enhanced Line Search: A Novel Method to Accelerate PARAFAC"*, SIAM J. Matrix Anal. Appl., Vol. 30, No. 3, pp. 1128-1147

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
@cswiercz These would be great additions!
I can give feedback directly on your branch prior to the PR if you'd like?
It might also be easier to break down the PR into smaller ones --e.g. one for augmenting the `kruskal_to_tensor` method to accept weights, etc.

My main preoccupation is to maintain a user friendly and intuitive API while adding these changes!

**Comment by cswiercz** [comment]
Looks like I need to learn Pytorch, especially if I'm going to add backend functionality...

**Comment by cswiercz** [comment]
Note that I force reset the `parafac-updates` remote branch so the commits this PR is representing is different from the commit messages above. Though, the "Commits" and "Files Changed" tabs seem to have been updated.

**Comment by cswiercz** [comment]
Got caught up in other work. Resuming work on this PR.

**Comment by JeanKossaifi** [comment]
Orthogonalisation added in f8782f6b65158dd08fccd7e8f3bf61786f7f4c27. 

Line search remains to add but is tricky to add without messing up the code.
We could add a version in a `contrib` submodule first and migrate to main functions once the API is stable and fixed.

**Comment by JeanKossaifi** [comment]
Added in 8d876cfbabce3472672c0f99e40092c361661b96

This should allow adding and trying new functionalities more easily/quickly!

**Comment by JeanKossaifi** [comment]
Closing the PR, opened issue #158 for the remaining item (line-search).

**Pull request closed without merging**
