### PR TITLE
Add nonneg cp decomposition

### PR DESCRIPTION
**Pull request by ahwillia**
Here is a prototype for what I mentioned here: https://github.com/tensorly/tensorly/issues/1

It could probably use a bit more documentation - but would love feedback at this stage. I added some short tests/checks in `examples/decomposition/`

If you like it I'm happy to edit and clean it up as you see fit.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thank you for your contribution, it would be interesting to have more decomposition methods.

When creating this project we wanted to keep dependencies to a minimum (NumPy and SciPy only, with a soft-dependency on Matplotlib) so we would prefer an alternative that doesn't involve extra-dependencies.

**Comment by ahwillia** [comment]
I really only need this file - https://github.com/kimjingu/nonnegfac-python/blob/master/nonnegfac/nnls.py

I'm going to copy it over to tensorly and paste the [license](https://github.com/kimjingu/nonnegfac-python/blob/master/LICENSE) at the top. Is this okay @kimjingu?

**Comment by kimjingu** [comment]
@ahwillia Fine with myself, but I'd leave the interpretation of the license up to you. A down side of copying is that the file can be left out from any future bug fixes. If you do, I'd recommend adding a comment with information of the original file and the citation info. 

Jingu Kim and Haesun Park. Fast Nonnegative Matrix Factorization: An Active-set-like Method And Comparisons. SIAM Journal on Scientific Computing (SISC), 33(6), pp. 3261-3281, 2011.

Thanks for your interest.

**Comment by JeanKossaifi** [comment]
Whilst I see the point, we would rather add tailored contributions as opposed to copying raw code from other projects (code rot, not updated as mentioned by Kim, etc). In the latter case it seems more appropriate to directly call the other library. 

You can still easily use this in your work and we could potentially modify the code to allow adding other solvers to make this easier.

Feel free to propose ideas in the mailing list https://groups.google.com/forum/#!forum/tensorly.

**Comment by nipunbatra** [comment]
In case using nnls.py from nonneg fac was a deal-breaker, then I wanted to chime in that scipy has an NNLS implementation. Here's a [small post](https://nipunbatra.github.io/blog/2017/nmf-nnls.html) I wrote for NNMF using NNLS.

**Pull request closed without merging**
