### PR TITLE
Fix mxnet testing

### PR DESCRIPTION
**Pull request by aarmey**
This fixes the mxnet testing by reverting to the stable pip-derived version. It lacks the fix for transposing tensors of mode > 6, but this is also the version users will have installed.

### CODE REVIEW

**Comment by caglayantuna** [comment]
That pip version was suggested [here](https://github.com/apache/incubator-mxnet/issues/18695) to fix this issue but it doesn't work properly. According to mxnet maintainers, fixed mxnet will be released after 2.x version and we have [1.9.1](https://pypi.org/project/mxnet/) for now.

**Comment by JeanKossaifi** [comment]
@aarmey -- should we give @merajhashemi's https://github.com/apache/incubator-mxnet/issues/18695#issuecomment-1188223249 a try? The MXNet team had recommended switching to 2.0 - we could update the documentation accordingly to instruct users to install the latest 2.x version of MXNet as well?

**Comment by aarmey** [comment]
I could've sworn I already tried that, but I always had the `<3` restriction. It seems to be working with v2. If all the tests pass here I'll merge.

**Comment by aarmey** [comment]
Aha. See the build logs—here is the issue I encountered earlier. Something having to do with tl.clip(). I'm not sufficiently familiar with mxnet to work it out.

```
tensorly/decomposition/_constrained_cp.py:149: in initialize_constrained_parafac
    factors[i] = proximal_operator(
tensorly/tenalg/proximal.py:399: in proximal_operator
    return tl.clip(tensor, tl.tensor(0.0), tl.max(tensor))
tensorly/backend/__init__.py:189: in wrapped_backend_method
    return getattr(
tensorly/backend/mxnet_backend.py:49: in clip
    return np.clip(tensor, a_min, a_max)
../../.local/lib/python3.10/site-packages/mxnet/numpy/multiarray.py:8047: in clip
    return _mx_nd_np.clip(a, a_min, a_max, out=out)
../../.local/lib/python3.10/site-packages/mxnet/ndarray/numpy/_op.py:5361: in clip
    return _api_internal.clip(a, a_min, a_max, out)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <mxnet._ffi.function.Function object at 0x7f1e8b3de400>
args = (array([[0.24348469, 0.06580535, 0.87321866],
       [0.01404733, 0.6605459 , 0.67318046],
       [0.53228605, 0.57758...0.3492678 , 0.24548139, 0.34916636],
       [0.19646972, 0.72570634, 0.7520379 ]]), array(0.), array(0.87321866), None)
temp_args = [], values = <mxnet._ffi._ctypes.function.MXNetValue_Array_4 object at 0x7f1da0beda40>
tcodes = <mxnet._ffi._ctypes.function.c_int_Array_4 object at 0x7f1da0bed9c0>

    def __call__(self, *args):
        """Call the function with positional arguments
    
        args : list
           The positional arguments to the function call.
        """
        temp_args = []
        values, tcodes, num_args = _make_mxnet_args(args, temp_args)
        ret_val = MXNetValue()
        ret_tcode = ctypes.c_int()
        if _LIB.MXNetFuncCall(
                self.handle, values, tcodes, ctypes.c_int(num_args),
                ctypes.byref(ret_val), ctypes.byref(ret_tcode)) != 0:
>           raise get_last_ffi_error()
E           mxnet.base.MXNetError: Traceback (most recent call last):
E             File "../include/mxnet/runtime/packed_func.h", line 410
E           MXNetError: Check failed: type_code_ == kDLFloat (11 vs. 2) : expected float but get NDArray
```

**Comment by JeanKossaifi** [comment]
Should we just swap back to 1.9 as you had and wait for 2.x to be stable then?

**Comment by aarmey** [comment]
Agreed. I've reverted back to the version using v1.9. I'm pretty sure there aren't other concerns with this so I'll merge.

**Comment by JeanKossaifi** [comment]
Thanks so much for the PRs fixing the tests @aarmey, finally back to all green!

**Pull request merged**
