### PR TITLE
Adds log function to tensorly

### PR DESCRIPTION
**Pull request by caglayantuna**

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Looks good, thanks @caglayantuna, merging.

**Comment by j6k4m8** [comment]
I think this still needs to be added to [the top-level `backend` method import list](https://github.com/tensorly/tensorly/blob/main/tensorly/__init__.py#L34), unless I'm misunderstanding?

**Comment by JeanKossaifi** [comment]
Yes, good point, thanks @j6k4m8!
Would be great to have a small PR for that and perhaps add some doc on how to add new functionalities to the backend.

**Comment by j6k4m8** [comment]
You got it!! :)

**Pull request merged**
